export const SET_USER_LOGIN = "SET_USER_LOGIN";
export const SET_USER_SIGNUP = "SET_USER_SIGNUP";

export const SET_INFO_USER = "SET_INFO_USER";
export const SET_USER = "SET_USER";
export const SET_THONG_TIN_NGUOI_DUNG = "SET_THONG_TIN_NGUOI_DUNG";
export const LAY_DANH_SACH_NGUOI_DUNG_THEO_NHOM =
  "LAY_DANH_SACH_NGUOI_DUNG_THEO_NHOM";
