export const LAY_DANH_SACH_PHIM = "LAY_DANH_SACH_PHIM"
export const INFO_FILMS = 'INFO_FILMS'
export const SET_PHIM_DANG_CHIEU = 'SET_PHIM_DANG_CHIEU'
export const SET_PHIM_SAP_CHIEU = 'SET_PHIM_SAP_CHIEU'
export const SET_THONG_TIN_PHIM = "SET_THONG_TIN_PHIM";
export const CAP_NHAT_PHIM = "CAP_NHAT_PHIM";